### ISSUE TITLE
Transparent label background for text field

### ISSUE THREAD

**Issue by Joozty** [oacore/design#200]
Currently, we can tweak a label background with [CSS variable](https://github.com/oacore/design/blob/master/src/elements/forms/text-field.css#L8). If the parent element has a different background colour as an input it doesn't look very well. Sometimes a user may want to use transparent background which should solve that look but there is a catch. If the user uses transparent background the underlying border is visible. Is there any possibility to fix it because I am out of ideas.

PS: We haven't had a use case yet so it should be rather considered as a nice to have.

![background](https://user-images.githubusercontent.com/12775440/85294547-10084a80-b49f-11ea-85cd-44f20104934d.PNG)

![transparent](https://user-images.githubusercontent.com/12775440/85294557-13033b00-b49f-11ea-8662-007ee7334883.PNG)

**Comment by viktor-yakubiv** [comment]
It is solved in [#199 (code block)](https://github.com/oacore/design/pull/199/files#diff-bae01b1a02ace66977103afc03f74ec9R53-R70) partially and is disabled (overridden by the line above) because it does not look good. There are a few major issues which I should be solved to make this happen:
- What if the input appears on the dark background? The label accessibility will be harmed, you can check it [from your example](https://webaim.org/resources/contrastchecker/?fcolor=AB5920&bcolor=424242).
- What if the input appears on the image? Contrast ratio goes completely unpredictable.

These 2 problems are very complex to solve. I considered 2 solutions:
1. Add a gradient fade from transparent to white for the top half of the label
   - It did not look good
2. Add a shadow around the test itself
   - A simple solution with a blurred white label did not look good
   - The more advanced solution with adding a 'stroke' around the text (that is how it works in Figma) is too painful to develop: we should add a shadow for each pixel we want to cover (about 8 shadows for one pixel around)

Since you already said we do not really need this,

> We haven't had a use case yet so it should be rather considered as a nice to have.

I assume, that the inputs should go on white always and close this issue.
