### ISSUE TITLE
className utility 

### ISSUE THREAD

**Issue by Joozty** [oacore/design#44]
There can be a collision in class names. Let's  have a text field component as an example:

When className prop contains for example `container` or whatever class defined in `text-fields.css`. It recognizes it as class name from the module.

```jsx
<TextField
  id="login-password"
  type="password"
  name="password"
  label="Password"
  className="container"
  placeholder="🔒 Something secure"
/>
```

Current output:

```
<div class="text-field-container-1W0Hy text-field-container-1W0Hy">...</div>
```

Expected output:
```
<div class="text-field-container-1W0Hy container">...</div>
```

**Comment by viktor-yakubiv** [comment]
I have another idea. Apply module only to the first class instance. If class name is duplicated, the first one only will be changed.

I do not really support this because it's not really clear. However, chain `className.use(...).from(module).join(className)` would be changed by prettier to 4 lines of code, what I do not like too.
